### ISSUE TITLE
No module named 'gdown'

### ISSUE THREAD

**Issue by gowestgis** [afruizh/TreeEyed#1]
I am using QGIS 3.28.9-Firenze on a Windows 11 machine.  When I install the TreeEyed plugin, it prompts me to install additional Python packages.  I say 'yes' and when it completes the Log file sshows it was successful but, then when I click on the TreeEyed plugin icon to run it, it again says 'Additional python packages are required to use this plugin.  I say 'yes' again and then it fails and I get the following messages in the Log file:

2024-10-31T19:57:43     WARNING    checking packages
2024-10-31T19:57:43     CRITICAL    Dependencies could not be imported
2024-10-31T19:57:43     CRITICAL    No module named 'gdown'
2024-10-31T19:57:48     WARNING    Installing additional packages canceled
2024-10-31T20:02:22     WARNING    checking packages
2024-10-31T20:02:22     CRITICAL    Dependencies could not be imported
2024-10-31T20:02:22     CRITICAL    No module named 'gdown'

If I look in the TreeEyed plugin dependencies folder (C:\Users\xxx\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\tree_eyed\dependencies), there are folders named 'gdown' and 'gdown-5.2.0.dist-info'.

In the gdown folder:
![gdown_folder](https://github.com/user-attachments/assets/9f4e997d-f272-40d3-a8ca-fbef5f82c0c5)\\

In the gdown-5.2.0.dist-info folder:
![gdowndist_folder](https://github.com/user-attachments/assets/bc72eda1-d665-4cf8-a890-1de40378489c)

Could you please advise on how I can resolve this issue.  Thank you.

**Comment by afruizh** [comment]
Thanks. I was able to reproduce it. It seems an additional QGIS restart is required after installing the python dependencies and downloading the models. I'll update the installation process. Are you able to use the plugin after restarting QGIS?

**Comment by gowestgis** [comment]
After I restarted QGIS, it asked 'Do you want to download the AI models? It may take a while.'  I clicked 'Yes' and chose the tree_eyed\dependencies folder to save them to. I can confirm in QGIS that the models are for Tree Eyed. It does seem I can then use the plugin.
If I close and restart QGIS, it does ask me again 'Do you want to download the AI models? It may take a while.'  I clicked 'No' and it appears the TreeEyed plugin is still available and QGIS opens without issue.
